services:
  parsing-service:
    build: .
    ports:
      - "8010:8000"
    env_file:
      - .env
    volumes:
      - ./app/debug:/app/app/debug
    restart: unless-stopped

  worker:
    build: .
    entrypoint: ["/entrypoint.sh"]
    command: ["python", "-m", "app.worker.run_worker"]
    env_file:
      - .env
    volumes:
      - ./app/debug:/app/app/debug
    restart: unless-stopped